import type { Metadata } from "next";
import "./globals.scss";
import Providers from "./providers";
import Header from "@/components/Header/Header";
import { ReactQueryProvider } from "./react-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Header />
          <ReactQueryProvider>
            {children}
            <div id="drawers-portal" />
          </ReactQueryProvider>
        </body>
      </html>
    </Providers>
  );
}
